version: '3.7'
services:
  # -----------------------
  zookeeper:
    image: 'bitnami/zookeeper:3.6.2'
    ports:
    - 2181:2181
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  # -----------------------
  kafka:
    image: 'bitnami/kafka:2.6.0'
    ports:
    - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper








